language: node_js
node_js:
- node
- 6
deploy:
  api_key:
    secure: RCTl/aBXCcDtU1qPPLVJHJy7VABLBBt2UnF5U0gdsWmEG4dUU8y23iEaKbD02ni+yrJQ8MDYlakejOTq4paSvLG6XOqkiT2/c+Xe7KbpNGZzyaI+tNbU0ZZldsDqGqonIhUlFpW8AucFo0xeXqLONz8SJwklUOPTnoqn3DdkgCKcI07/2BNPMNm4y8X/1KIR3zgq5UJlr3yfLE3eK85sYn0qLKbqEgAY2C9zVhRpR0OYw8EKNMZgYDOUrEHnw1H58pf3rOdHII2vGJTCdYilAEepNYn2CEQmtpD3GU+f38JCxCIy/SabLivME6dHETBZJRJ2IVFhqr/eBkrg1LZN6dJAkohnNp76vOTYW7Z2iU63GiyNthMBNacYdRMmad/9UnU4heHHbRxluw0wPGJTMp+MhiSUPOSlZKwwwefiYqbwmcpVB6A7b+rcFg6Qx/Vi2AtB/kKsklTr93+ja0SvEOYLzOj3VAxq5Rymp59r2wZ/lH6lSkm2F6I4DJ1OMJZeX/UZ2YsjDvbaE7SFHwifKp0kpxYPD3aZe2sWY5yPx8KQ6zPiJ4GhnG8Nn+tPFzTVZGeea/mfrPsDLhsEWdH99CzTaFHrbkx4iVEY1nqO+UPxkvTiDXy4WSkEpd5PrBJCW0Yt/nw8YwDMGceyHR9Y+F7D+iNusxg0H8OqUf/nb/w=
  email: al@builtbybrayne.com
  provider: npm
  on:
    tags: true
notifications:
  slack:
    secure: E2SeRRsgp/t+ibiEYoV2R+lkZ0QeI758qMwPbA4TcTp7xDUAPKO0VuIcgWMg4C+PdRBUfJRvmiciJi1uMUiIXRyMmkgAA+E+ofaZnBiiO9elR+tm+dBKFWG4W2lS3j8FGjtZCtohAyIhHpdOVoge5zUiomDoOoehqm1abrrFS4zDtJaffZqnbLvpqV7Vo5MFXOJ6sbezX/oWN93Jvwz9SwHS3+FilEs9pZIJS6Mqz7JXOqqDMYI7VeojGw1ehtVUfso4OtGBHJNQIAEfQQH63SZFm3cXnTDQlwfIaAbWPy5eQfzMgJMyRgCylfRMy0pcVqEmuQRJW+gBz839yD5CvNdc0Cr89tylpTJbqvl7yCR/St8RJ5Yf1MD3/g603/pBRTDfGqTrp/C46an7onrw4lfz5Ew1mbgaj06hbscNlB4Ho+m2s/hap2gd6GgL1oQw9HkS4n2VVQIpqZ/lmFl0BYj4NMGlQ4LKLGCUTfj3aP9xMRw18TBeB481FjKUIRVOnu4wVUAKtRqieLMoM3XWqAXyWsHQTD12wcICyAzlfi1xqwGTV5BLIZegj2k7qRxHHOoCb5idrI3rOxXktTaTprZlUWwEc/WD7EGJBdFG/0gDWLS3oXCRncrAHckD3Qd2k0xlKscNgyTq1LEM4+XBLJSupuOqmHEm8V1whoFtVzI=
